#############################################################################
# Makefile for building: optimizacionac
# Generated by qmake (3.0) (Qt 5.1.0) on: mié jul 30 21:33:01 2014
# Project:  optimizacionac.pro
# Template: app
# Command: /home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile optimizacionac.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/linux-g++ -I. -I../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include -I../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets -I../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui -I../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc -Wl,-rpath,/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib
LIBS          = $(SUBLIBS) -L/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		individual.cpp \
		situationalknowledge.cpp \
		normativeknowledge.cpp \
		normativeknowledgevariable.cpp \
		populationvariation.cpp moc_mainwindow.cpp \
		moc_individual.cpp \
		moc_situationalknowledge.cpp \
		moc_normativeknowledge.cpp \
		moc_normativeknowledgevariable.cpp \
		moc_populationvariation.cpp
OBJECTS       = main.o \
		mainwindow.o \
		individual.o \
		situationalknowledge.o \
		normativeknowledge.o \
		normativeknowledgevariable.o \
		populationvariation.o \
		moc_mainwindow.o \
		moc_individual.o \
		moc_situationalknowledge.o \
		moc_normativeknowledge.o \
		moc_normativeknowledgevariable.o \
		moc_populationvariation.o
DIST          = ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/spec_pre.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/shell-unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/linux.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/gcc-base.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/g++-base.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/g++-unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/qconfig.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt_functions.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt_config.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/spec_post.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/default_pre.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/default_pre.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/resolve_config.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/default_post.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qml_debug.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/declarative_debug.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/warn_on.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/resources.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/moc.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/opengl.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/uic.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/thread.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/wayland-scanner.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/testcase_targets.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/exceptions.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/yacc.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/lex.prf \
		optimizacionac.pro \
		optimizacionac.pro
QMAKE_TARGET  = optimizacionac
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = optimizacionac


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: optimizacionac.pro ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/linux-g++/qmake.conf ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/spec_pre.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/shell-unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/linux.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/gcc-base.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/g++-base.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/g++-unix.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/qconfig.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt_functions.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt_config.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/spec_post.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/default_pre.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/default_pre.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/resolve_config.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/default_post.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qml_debug.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/declarative_debug.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/warn_on.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/resources.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/moc.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/opengl.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/uic.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/thread.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/wayland-scanner.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/testcase_targets.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/exceptions.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/yacc.prf \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/lex.prf \
		optimizacionac.pro \
		/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib/libQt5Widgets.prl \
		/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib/libQt5Gui.prl \
		/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile optimizacionac.pro
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/spec_pre.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/shell-unix.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/unix.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/linux.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/gcc-base.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/g++-base.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/common/g++-unix.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/qconfig.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_bootstrap.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_clucene.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_core.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_designer.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_designercomponents.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_gui.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_help.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_network.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_platformsupport.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qml.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_quick.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_quickparticles.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_script.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_sql.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_svg.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_v8.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_xml.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt_functions.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt_config.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/linux-g++/qmake.conf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/spec_post.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/exclusive_builds.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/default_pre.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/default_pre.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/resolve_config.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/default_post.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qml_debug.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/declarative_debug.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/warn_on.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/qt.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/resources.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/moc.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/opengl.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/uic.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/unix/thread.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/wayland-scanner.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/testcase_targets.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/exceptions.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/yacc.prf:
../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/mkspecs/features/lex.prf:
optimizacionac.pro:
/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib/libQt5Widgets.prl:
/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib/libQt5Gui.prl:
/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile optimizacionac.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/optimizacionac1.0.0 || mkdir -p .tmp/optimizacionac1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/optimizacionac1.0.0/ && $(COPY_FILE) --parents mainwindow.h individual.h situationalknowledge.h normativeknowledge.h normativeknowledgevariable.h populationvariation.h .tmp/optimizacionac1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp individual.cpp situationalknowledge.cpp normativeknowledge.cpp normativeknowledgevariable.cpp populationvariation.cpp .tmp/optimizacionac1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/optimizacionac1.0.0/ && (cd `dirname .tmp/optimizacionac1.0.0` && $(TAR) optimizacionac1.0.0.tar optimizacionac1.0.0 && $(COMPRESS) optimizacionac1.0.0.tar) && $(MOVE) `dirname .tmp/optimizacionac1.0.0`/optimizacionac1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/optimizacionac1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_individual.cpp moc_situationalknowledge.cpp moc_normativeknowledge.cpp moc_normativeknowledgevariable.cpp moc_populationvariation.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_individual.cpp moc_situationalknowledge.cpp moc_normativeknowledge.cpp moc_normativeknowledgevariable.cpp moc_populationvariation.cpp
moc_mainwindow.cpp: ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/QMainWindow \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qmainwindow.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qwindowdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmargins.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrect.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsize.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpoint.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpaintdevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpalette.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qcolor.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qrgb.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdatastream.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiodevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpair.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qregexp.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringmatcher.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qbrush.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvector.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qmatrix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpolygon.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qregion.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qline.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qtransform.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpainterpath.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qimage.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpixmap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qshareddata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qhash.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfont.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfontmetrics.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfontinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qcursor.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qkeysequence.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvariant.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdebug.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtextstream.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlocale.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qset.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontiguouscache.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qurl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qurlquery.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfile.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfiledevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qvector2d.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qtouchdevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qtabwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qicon.h \
		mainwindow.h
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_individual.cpp: ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		individual.h
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include individual.h -o moc_individual.cpp

moc_situationalknowledge.cpp: ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		individual.h \
		situationalknowledge.h
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include situationalknowledge.h -o moc_situationalknowledge.cpp

moc_normativeknowledge.cpp: ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		normativeknowledgevariable.h \
		individual.h \
		normativeknowledge.h
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include normativeknowledge.h -o moc_normativeknowledge.cpp

moc_normativeknowledgevariable.cpp: ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		normativeknowledgevariable.h
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include normativeknowledgevariable.h -o moc_normativeknowledgevariable.cpp

moc_populationvariation.cpp: ../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QList \
		individual.h \
		situationalknowledge.h \
		normativeknowledge.h \
		normativeknowledgevariable.h \
		populationvariation.h
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include populationvariation.h -o moc_populationvariation.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/antonio/desarrollo/qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/QMainWindow \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qmainwindow.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qwindowdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmargins.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrect.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsize.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpoint.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpaintdevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpalette.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qcolor.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qrgb.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdatastream.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiodevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpair.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qregexp.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringmatcher.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qbrush.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvector.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qmatrix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpolygon.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qregion.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qline.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qtransform.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpainterpath.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qimage.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpixmap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qshareddata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qhash.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfont.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfontmetrics.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfontinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qcursor.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qkeysequence.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvariant.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdebug.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtextstream.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlocale.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qset.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontiguouscache.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qurl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qurlquery.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfile.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfiledevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qvector2d.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qtouchdevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qtabwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qicon.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/QApplication \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qapplication.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreapplication.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qeventloop.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qguiapplication.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/QMainWindow \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qmainwindow.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qwindowdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmargins.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrect.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsize.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpoint.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpaintdevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpalette.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qcolor.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qrgb.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdatastream.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiodevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpair.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qregexp.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringmatcher.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qbrush.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvector.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qmatrix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpolygon.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qregion.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qline.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qtransform.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpainterpath.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qimage.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qpixmap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qshareddata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qhash.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfont.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfontmetrics.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qfontinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qcursor.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qkeysequence.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvariant.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdebug.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtextstream.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlocale.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qset.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontiguouscache.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qurl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qurlquery.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfile.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfiledevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qvector2d.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qtouchdevice.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtWidgets/qtabwidget.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtGui/qicon.h \
		ui_mainwindow.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QTime \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdatetime.h \
		individual.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		situationalknowledge.h \
		normativeknowledge.h \
		normativeknowledgevariable.h \
		populationvariation.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

individual.o: individual.cpp individual.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QTime \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qdatetime.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qshareddata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qhash.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o individual.o individual.cpp

situationalknowledge.o: situationalknowledge.cpp situationalknowledge.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		individual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o situationalknowledge.o situationalknowledge.cpp

normativeknowledge.o: normativeknowledge.cpp normativeknowledge.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		normativeknowledgevariable.h \
		individual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normativeknowledge.o normativeknowledge.cpp

normativeknowledgevariable.o: normativeknowledgevariable.cpp normativeknowledgevariable.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normativeknowledgevariable.o normativeknowledgevariable.cpp

populationvariation.o: populationvariation.cpp populationvariation.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QObject \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qnamespace.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobal.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qconfig.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qfeatures.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsystemdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcompilerdetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qprocessordetection.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qglobalstatic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qgenericatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_msvc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_integrity.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_power.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_alpha.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv7.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv6.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_armv5.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_bfin.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_ia64.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_mips.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_s390.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_sparc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_x86.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_gcc.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qatomic_unix.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmutex.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlogging.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qflags.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypeinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qtypetraits.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qsysinfo.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstring.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qchar.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qbytearray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qrefcount.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qarraydata.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qstringbuilder.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qlist.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qalgorithms.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qiterator.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcoreevent.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qscopedpointer.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qmetatype.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qvarlengtharray.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qcontainerfwd.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qisenum.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/qobject_impl.h \
		../../../qt-5.1-rc/Qt5.1.0/5.1.0-rc1/gcc/include/QtCore/QList \
		individual.h \
		situationalknowledge.h \
		normativeknowledge.h \
		normativeknowledgevariable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o populationvariation.o populationvariation.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_individual.o: moc_individual.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_individual.o moc_individual.cpp

moc_situationalknowledge.o: moc_situationalknowledge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_situationalknowledge.o moc_situationalknowledge.cpp

moc_normativeknowledge.o: moc_normativeknowledge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_normativeknowledge.o moc_normativeknowledge.cpp

moc_normativeknowledgevariable.o: moc_normativeknowledgevariable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_normativeknowledgevariable.o moc_normativeknowledgevariable.cpp

moc_populationvariation.o: moc_populationvariation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_populationvariation.o moc_populationvariation.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

